### PR TITLE
Skip progress indicators if running in non-interactive mode

### LINKED ISSUE #3292: nsg functions need to be able to retry when they hit EAGAIN
0.10.6 / npm / linux

This is generally triggered by running lots of operations in parallel - such as to quickyl update a bunch of security rules. Ideally the app should have retry a few times (tunable on command line?) with backoff. Likely exists in other subsystems as well, but the NSG ones are most visible to me cause of the volume of them. 

```

2016-11-02T20:59:57.981Z:
{ [Error: EAGAIN: resource temporarily unavailable, write]
  stack: [Getter/Setter],
  errno: -11,
  code: 'EAGAIN',
  syscall: 'write',
  __frame: 
   { name: 'createRule__7',
     line: 154,
     file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js',
     prev: 
      { name: '__66',
        line: 1385,
        file: '/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js',
        prev: undefined,
        calls: 1,
        active: false,
        offset: 8,
        col: 10 },
     calls: 1,
     active: false,
     offset: 6,
     col: 19 },
  rawStack: [Getter] }
Error: EAGAIN: resource temporarily unavailable, write
  <<< async stack >>>
    at Error (native)
    at Object.fs.writeSync (fs.js:664:18)
    at Interactor.__.extend.progress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:134:8)
    at get__6 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:137:35)
  at createRule__7 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:160:20)
  at __66 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:1393:11)
  <<< raw stack >>>
    at Error (native)
    at Object.fs.writeSync (fs.js:664:18)
    at Interactor.__.extend.progress (/usr/local/lib/node_modules/azure-cli/lib/util/interaction.js:134:8)
    at __$get__6 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:137:35)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.get__6 [as get] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:135:149)
    at __$createRule__7 (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:160:19)
    at __func (/usr/local/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Nsg.createRule__7 [as createRule] (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/nsg.js:154:207)
    at ___ (/usr/local/lib/node_modules/azure-cli/lib/commands/arm/network/network.js:1393:26)

```

### PR DESCRIPTION
**Pull request by nneul**
The content to be added to Changelog is as follows:
* Skip output of progress spinners when running with AZURE_NON_INTERACTIVE_MODE set

mostly resolves #3292

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nneul__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

File: lib/util/interaction.js [hunk 1]
```diff
@@ -81,7 +84,9 @@ __.extend(Interactor.prototype, {
         clearInterval(self.activeProgressTimer);
         self.activeProgressTimer = null;
       }
-      fs.writeSync(1, '\r+\n');
+      if ( ! nonInteractiveMode ) {
```
Comment (amarzavery) [inline lib/util/interaction.js]: if (!nonInteractiveMode) {

**Comment by amarzavery** [comment]
overall LGTM

**Comment by nneul** [comment]
Changes made as requested.
